// Puts the generated banner at the top of a repository's README.
//   node tools/brand/readme.mjs <checkout-dir> <Repo>
// Copies the four banner SVGs into docs/brand/ and inserts a <picture> banner (light/dark,
// wide/phone) and a row of links that exist ABOVE the first H1, which stays as written.
// Nothing else in the README changes. Re-running replaces only the marked block.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const SITE = 'https://homenshum.github.io';
const START = '<!-- brand:start — generated by github.com/HomenShum/HomenShum.github.io (tools/brand); edit there, not here -->';
const END = '<!-- brand:end -->';
const FILES = ['banner-light.svg', 'banner-dark.svg', 'compact-light.svg', 'compact-dark.svg'];

const norm = s => s.toLowerCase().replace(/[^\p{L}\p{N}]+/gu, '');
// GitHub's heading anchor: lowercase, drop punctuation, spaces become hyphens.
const anchor = h => h.trim().toLowerCase().replace(/[^\p{L}\p{N}\s_-]/gu, '').replace(/\s/g, '-');

export function header(r, m, readme) {
  const slug = r.repo.toLowerCase();
  const name = r.name || r.repo;
  const quick = (readme.match(/^#{2,3} +(quick ?start.*)$/im) || [])[1];
  // A homepage is a live demo only if it is neither GitHub itself nor this portfolio.
  const live = m.homepage && !/^https:\/\/(github\.com|homenshum\.github\.io)\//.test(m.homepage) ? m.homepage : null;
  const nav = [
    quick && ['Quickstart', `#${anchor(quick)}`],
    m.startHere && ['Code walkthrough', 'docs/START_HERE.md'],
    m.handoff && ['Handoff', 'HANDOFF.md'],
    live && [r.liveLabel || 'Live demo', live],
    ['All projects', `${SITE}/`],
  ].filter(Boolean);
  const alt = `${name}: ${r.tagline}`.replace(/"/g, '&quot;');
  return `${START}
<a href="${SITE}/${slug}/">
  <picture>
    <source media="(max-width: 600px) and (prefers-color-scheme: dark)" srcset="docs/brand/compact-dark.svg">
    <source media="(max-width: 600px)" srcset="docs/brand/compact-light.svg">
    <source media="(prefers-color-scheme: dark)" srcset="docs/brand/banner-dark.svg">
    <img alt="${alt}" src="docs/brand/banner-light.svg" width="100%">
  </picture>
</a>

<p align="center">${nav.map(([label, href]) => `<a href="${href}">${label.replace(/ /g, "&nbsp;")}</a>`).join(' · ')}</p>
${END}`;
}

export function apply(readme, block, tagline) {
  if (readme.includes(START)) {
    const a = readme.indexOf(START), b = readme.indexOf(END, a);
    if (b < 0) throw new Error('brand:start without brand:end');
    return readme.slice(0, a) + block + readme.slice(b + END.length);
  }
  const lines = readme.split('\n');
  let fence = false, h1 = -1;
  for (let i = 0; i < lines.length; i++) {
    if (/^\s*(```|~~~)/.test(lines[i])) fence = !fence;
    if (!fence && (/^# \S/.test(lines[i]) || /^<h1[\s>]/i.test(lines[i].trim()))) { h1 = i; break; }
  }
  if (h1 < 0) throw new Error('no H1 to place the banner above');
  const out = [...lines];
  // A subtitle that repeats the banner's tagline word for word is dropped: the banner says it.
  let next = h1 + 1;
  while (next < out.length && out[next].trim() === '') next++;
  const sub = (out[next] || '').match(/^#{2,3} +(.+)$/);
  const drop = sub && norm(sub[1]) === norm(tagline) ? next : -1;
  const blockLines = block.split('\n');
  out.splice(h1, 0, ...blockLines, '');
  if (drop > -1) out.splice(drop + blockLines.length + 1, 1);
  return out.join('\n');
}

// Whole-file rewrite that keeps the file's own line endings (several repos are CRLF).
export function rewrite(raw, r, m) {
  const eol = raw.includes('\r\n') ? '\r\n' : '\n';
  const readme = raw.replace(/\r\n/g, '\n');
  return apply(readme, header(r, m, readme), r.tagline).replace(/\n/g, eol);
}

if (path.resolve(process.argv[1] || '') === fileURLToPath(import.meta.url)) {
  const [dir, repo] = process.argv.slice(2);
  const r = JSON.parse(fs.readFileSync(path.join(root, 'tools/brand/repos.json'), 'utf8')).find(x => x.repo === repo);
  const m = JSON.parse(fs.readFileSync(path.join(root, 'tools/site/meta.json'), 'utf8'))[repo];
  if (!r || !m) throw new Error(`unknown repo ${repo}`);
  fs.mkdirSync(path.join(dir, 'docs/brand'), { recursive: true });
  for (const f of FILES) fs.copyFileSync(path.join(root, 'brand', repo, f), path.join(dir, 'docs/brand', f));
  const file = path.join(dir, 'README.md');
  const raw = fs.readFileSync(file, 'utf8');
  fs.writeFileSync(file, rewrite(raw, r, m));
  console.log(`${repo}: README header ${raw.includes(START) ? 'refreshed' : 'inserted'}`);
}
